### ISSUE TITLE
import dataset

### ISSUE THREAD

**Issue by hongcui** [biosemantics/oto#36]
For the first two times, I input the dataset name, but they didn't show in the right window. So, I could not import terms.
I tried to delete them through Admin Tasks. One message shows:

Technical details of the error : java.lang.NullPointerException.

see http://screencast.com/t/2yOqZqmajaH

**Comment by danveno** [comment]
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Incorrect table name 'Plant_habitat_Spring2016_jin_mao_20160506123553_web_grouped_terms'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)




It sounds like the table name is too long.

**Comment by danveno** [comment]
set the maximum length of dataset name plus user's last name to 32.
